version: "3"

services:
  compute_server:
    image: alchemine/base-cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    hostname: "dev"
    ports:
      - 10022:22   # SSH
      - 8501:8501  # streamlit
      - 8888:8888  # jupyter
    volumes:
      - /root/project/initial-repository:/root/initial-repository
      - /data:/data
    restart: always
    ipc: host
    tty: true
    privileged: true
